[[CUDNN_CUDA101]]
arch = "x86_64"
git-tree-sha1 = "65e3425ecb85689a1b04750fb6484cecfafab25b"
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA101.download]]
    sha256 = "340271e2131bafb23ddbf04c26414d8cc7a0ec69731088c69e345c71dc77557a"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA101_jll.jl/releases/download/CUDNN_CUDA101-v8.0.2+0/CUDNN_CUDA101.v8.0.2.x86_64-linux-gnu.tar.gz"
[[CUDNN_CUDA101]]
arch = "powerpc64le"
git-tree-sha1 = "baaf4a1efdeade6368c51aff26b394eec48cfab8"
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA101.download]]
    sha256 = "758c6837fe61c50ff23cf19b6ea6852c45fb398d7c327e3df08442879be79d46"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA101_jll.jl/releases/download/CUDNN_CUDA101-v8.0.2+0/CUDNN_CUDA101.v8.0.2.powerpc64le-linux-gnu.tar.gz"
[[CUDNN_CUDA101]]
arch = "x86_64"
git-tree-sha1 = "f52953d0bfb0d4a6d04643cdb71566850adaf167"
os = "windows"

    [[CUDNN_CUDA101.download]]
    sha256 = "30c2a1eafef25fac6188891d23c8ead760d73c8029c1f830ae0b6b5ef4341013"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA101_jll.jl/releases/download/CUDNN_CUDA101-v8.0.2+0/CUDNN_CUDA101.v8.0.2.x86_64-w64-mingw32.tar.gz"
